version: '3.8'
services:
  compress-app:
    image: compress-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    env_file:
      - .env

volumes:
  node_modules:
  build: